# Generated by Django 5.0.7 on 2024-10-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='start_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
